using System;
using System.Collections.Generic;

namespace VoiceCommand {
	public class VoiceCommand {
		public List<string> Commands;
		public VoiceCommandAction Action;
		public VoiceCommandArea Area=VoiceCommandArea.Global;
	}	

	public enum VoiceCommandAction {
		SelectPatient,
		GoToChartModule,
		GoToAppointmentModule,
		GoToFamilyModule,
		GoToAccountModule,
		GoToTreatmentPlanModule,
		GoToImageModule,
		GoToManageModule,
		CreateCommlog,
		SendEmail,
		CreatePatientForm,
		CreatePatientPayment,
		OpenPerioChart,
		CreatePerioChart,
		Two,
		One,
		Three,
		Four,
		Five,
		Six,
		Seven,
		Eight,
		Nine,
		Ten,
		Eleven,
		Twelve,
		Thirteen,
		Fourteen,
		Fifteen,
		Sixteen,
		Seventeen,
		Eightteen,
		Nineteen,
		Zero,
		Triplet,
		Bleeding,
		Calculus,
		Suppuration,
		Plaque,
		Backspace,
		SkipToTooth,
		Left,
		Right,
		Delete,
		CopyPrevious,
		StartListening,
		StopListening,
		GiveFeedback,
		StopGivingFeedback,
		DidntGetThat,
		SkipToToothOneFacial,
		SkipToToothTwoFacial,
		SkipToToothFourFacial,
		SkipToToothThreeFacial,
		SkipToToothFiveFacial,
		SkipToToothSixFacial,
		SkipToToothSevenFacial,
		SkipToToothEightFacial,
		SkipToToothNineFacial,
		SkipToToothTenFacial,
		SkipToToothElevenFacial,
		SkipToToothTwelveFacial,
		SkipToToothThirteenFacial,
		SkipToToothFourteenFacial,
		SkipToToothFifteenFacial,
		SkipToToothSixteenFacial,
		SkipToTootSeventeenFacial,
		SkipToToothEighteenFacial,
		SkipToToothNineteenFacial,
		SkipToToothTwentyFacial,
		SkipToToothTwentyOneFacial,
		SkipToToothTwentyTwoFacial,
		SkipToToothTwentyThreeFacial,
		SkipToToothTwentyFourFacial,
		SkipToToothTwentyFiveFacial,
		SkipToToothTwentySixFacial,
		SkipToToothTwentySevenFacial,
		SkipToToothTwentyEightFacial,
		SkipToToothTwentyNineFacial,
		SkipToToothThirtyFacial,
		SkipToToothThirtyOneFacial,
		SkipToToothThirtyTwoFacial,
		SkipToToothOneLabial,
		SkipToToothTwoLabial,
		SkipToToothFourLabial,
		SkipToToothThreeLabial,
		SkipToToothFiveLabial,
		SkipToToothSixLabial,
		SkipToToothSevenLabial,
		SkipToToothEightLabial,
		SkipToToothNineLabial,
		SkipToToothTenLabial,
		SkipToToothElevenLabial,
		SkipToToothTwelveLabial,
		SkipToToothThirteenLabial,
		SkipToToothFourteenLabial,
		SkipToToothFifteenLabial,
		SkipToToothSixteenLabial,
		SkipToTootSeventeenLabial,
		SkipToToothEighteenLabial,
		SkipToToothNineteenLabial,
		SkipToToothTwentyLabial,
		SkipToToothTwentyOneLabial,
		SkipToToothTwentyTwoLabial,
		SkipToToothTwentyThreeLabial,
		SkipToToothTwentyFourLabial,
		SkipToToothTwentyFiveLabial,
		SkipToToothTwentySixLabial,
		SkipToToothTwentySevenLabial,
		SkipToToothTwentyEightLabial,
		SkipToToothTwentyNineLabial,
		SkipToToothThirtyLabial,
		SkipToToothThirtyOneLabial,
		SkipToToothThirtyTwoLabial,
	}

	[Flags]
	public enum VoiceCommandArea {
		Global=0,
		PerioChart=1,
		FormOpenDental = 2
	}
}
