/*==================================================================================
This file is a part of Voice Command.
Copyright 2017  Christopher A. McGehee

Voice Command is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Voice Command is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
===================================================================================*/
using System;
using System.Collections.Generic;

namespace VoiceCommand {
	public class VoiceCommand {
		public List<string> Commands;
		public VoiceCommandAction Action;
		public VoiceCommandArea Area=VoiceCommandArea.Global;
	}	

	public enum VoiceCommandAction {
		SelectPatient,
		GoToChartModule,
		GoToAppointmentModule,
		GoToFamilyModule,
		GoToAccountModule,
		GoToTreatmentPlanModule,
		GoToImageModule,
		GoToManageModule,
		CreateCommlog,
		SendEmail,
		CreatePatientForm,
		CreatePatientPayment,
		OpenPerioChart,
		CreatePerioChart,
		Two,
		One,
		Three,
		Four,
		Five,
		Six,
		Seven,
		Eight,
		Nine,
		Ten,
		Eleven,
		Twelve,
		Thirteen,
		Fourteen,
		Fifteen,
		Sixteen,
		Seventeen,
		Eightteen,
		Nineteen,
		Zero,
		Triplet,
		Bleeding,
		Calculus,
		Suppuration,
		Plaque,
		Backspace,
		SkipToothOne,
		SkipToothTwo,
		SkipToothThree,
		SkipToothFour,
		SkipToothFive,
		SkipToothSix,
		SkipToothSeven,
		SkipToothEight,
		SkipToothNine,
		SkipToothTen,
		SkipToothEleven,
		SkipToothTwelve,
		SkipToothThirteen,
		SkipToothFourteen,
		SkipToothFifteen,
		SkipToothSixteen,
		SkipToothSeventeen,
		SkipToothEighteen,
		SkipToothNineteen,
		SkipToothTwenty,
		SkipToothTwentyOne,
		SkipToothTwentyTwo,
		SkipToothTwentyThree,
		SkipToothTwentyFour,
		SkipToothTwentyFive,
		SkipToothTwentySix,
		SkipToothTwentySeven,
		SkipToothTwentyEight,
		SkipToothTwentyNine,
		SkipToothThirty,
		SkipToothThirtyOne,
		SkipToothThirtyTwo,
		Left,
		Right,
		Delete,
		CopyPrevious,
		StartListening,
		StopListening,
		GiveFeedback,
		StopGivingFeedback,
		DidntGetThat,
		GoToToothOneFacial,
		GoToToothTwoFacial,
		GoToToothFourFacial,
		GoToToothThreeFacial,
		GoToToothFiveFacial,
		GoToToothSixFacial,
		GoToToothSevenFacial,
		GoToToothEightFacial,
		GoToToothNineFacial,
		GoToToothTenFacial,
		GoToToothElevenFacial,
		GoToToothTwelveFacial,
		GoToToothThirteenFacial,
		GoToToothFourteenFacial,
		GoToToothFifteenFacial,
		GoToToothSixteenFacial,
		GoToToothSeventeenFacial,
		GoToToothEighteenFacial,
		GoToToothNineteenFacial,
		GoToToothTwentyFacial,
		GoToToothTwentyOneFacial,
		GoToToothTwentyTwoFacial,
		GoToToothTwentyThreeFacial,
		GoToToothTwentyFourFacial,
		GoToToothTwentyFiveFacial,
		GoToToothTwentySixFacial,
		GoToToothTwentySevenFacial,
		GoToToothTwentyEightFacial,
		GoToToothTwentyNineFacial,
		GoToToothThirtyFacial,
		GoToToothThirtyOneFacial,
		GoToToothThirtyTwoFacial,
		GoToToothOneLingual,
		GoToToothTwoLingual,
		GoToToothFourLingual,
		GoToToothThreeLingual,
		GoToToothFiveLingual,
		GoToToothSixLingual,
		GoToToothSevenLingual,
		GoToToothEightLingual,
		GoToToothNineLingual,
		GoToToothTenLingual,
		GoToToothElevenLingual,
		GoToToothTwelveLingual,
		GoToToothThirteenLingual,
		GoToToothFourteenLingual,
		GoToToothFifteenLingual,
		GoToToothSixteenLingual,
		GoToToothSeventeenLingual,
		GoToToothEighteenLingual,
		GoToToothNineteenLingual,
		GoToToothTwentyLingual,
		GoToToothTwentyOneLingual,
		GoToToothTwentyTwoLingual,
		GoToToothTwentyThreeLingual,
		GoToToothTwentyFourLingual,
		GoToToothTwentyFiveLingual,
		GoToToothTwentySixLingual,
		GoToToothTwentySevenLingual,
		GoToToothTwentyEightLingual,
		GoToToothTwentyNineLingual,
		GoToToothThirtyLingual,
		GoToToothThirtyOneLingual,
		GoToToothThirtyTwoLingual,
		Probing,
		MucoGingivalJunction,
		GingivalMargin,
		Furcation,
		Mobility,
		PlusOne,
		PlusTwo,
		PlusThree,
		PlusFour,
		PlusFive,
		PlusSix,
		PlusSeven,
		PlusNine,
		PlusEight,
		SkipCurrentTooth,
		Ok,
		Cancel,
		Yes,
		No
	}

	[Flags]
	public enum VoiceCommandArea {
		Global=0,
		PerioChart=1,
		FormOpenDental=2,
		VoiceMsgBox=4
	}
}
